"""
Recipe Data Module — Agent 2 (Backend/AI)
Contains the ingredient database and recipe database for the recommendation system.
"""

INGREDIENT_CATEGORIES = {
    "vegetables": {
        "emoji": "🥬",
        "items": [
            {"id": "tomato", "name": "Tomato", "emoji": "🍅"},
            {"id": "onion", "name": "Onion", "emoji": "🧅"},
            {"id": "garlic", "name": "Garlic", "emoji": "🧄"},
            {"id": "potato", "name": "Potato", "emoji": "🥔"},
            {"id": "carrot", "name": "Carrot", "emoji": "🥕"},
            {"id": "bell_pepper", "name": "Bell Pepper", "emoji": "🫑"},
            {"id": "spinach", "name": "Spinach", "emoji": "🥬"},
            {"id": "broccoli", "name": "Broccoli", "emoji": "🥦"},
            {"id": "mushroom", "name": "Mushroom", "emoji": "🍄"},
            {"id": "corn", "name": "Corn", "emoji": "🌽"},
            {"id": "cucumber", "name": "Cucumber", "emoji": "🥒"},
            {"id": "lettuce", "name": "Lettuce", "emoji": "🥬"},
            {"id": "peas", "name": "Peas", "emoji": "🫛"},
            {"id": "cauliflower", "name": "Cauliflower", "emoji": "🥦"},
            {"id": "eggplant", "name": "Eggplant", "emoji": "🍆"},
            {"id": "zucchini", "name": "Zucchini", "emoji": "🥒"},
            {"id": "cabbage", "name": "Cabbage", "emoji": "🥬"},
            {"id": "ginger", "name": "Ginger", "emoji": "🫚"},
            {"id": "avocado", "name": "Avocado", "emoji": "🥑"},
            {"id": "green_beans", "name": "Green Beans", "emoji": "🫛"},
            {"id": "spring_onion", "name": "Spring Onion", "emoji": "🧅"},
            {"id": "green_chili", "name": "Green Chili", "emoji": "🌶️"},
            {"id": "curry_leaves", "name": "Curry Leaves", "emoji": "🌿"},
        ]
    },
    "proteins": {
        "emoji": "🍗",
        "items": [
            {"id": "chicken", "name": "Chicken", "emoji": "🍗"},
            {"id": "egg", "name": "Egg", "emoji": "🥚"},
            {"id": "beef", "name": "Beef", "emoji": "🥩"},
            {"id": "shrimp", "name": "Shrimp", "emoji": "🦐"},
            {"id": "fish", "name": "Fish", "emoji": "🐟"},
            {"id": "tofu", "name": "Tofu", "emoji": "🧊"},
            {"id": "paneer", "name": "Paneer", "emoji": "🧀"},
            {"id": "lamb", "name": "Lamb", "emoji": "🍖"},
            {"id": "lentils", "name": "Lentils", "emoji": "🫘"},
            {"id": "chickpeas", "name": "Chickpeas", "emoji": "🫘"},
            {"id": "black_beans", "name": "Black Beans", "emoji": "🫘"},
        ]
    },
    "dairy": {
        "emoji": "🧈",
        "items": [
            {"id": "milk", "name": "Milk", "emoji": "🥛"},
            {"id": "cheese", "name": "Cheese", "emoji": "🧀"},
            {"id": "butter", "name": "Butter", "emoji": "🧈"},
            {"id": "cream", "name": "Cream", "emoji": "🥛"},
            {"id": "yogurt", "name": "Yogurt", "emoji": "🥛"},
        ]
    },
    "grains": {
        "emoji": "🌾",
        "items": [
            {"id": "rice", "name": "Rice", "emoji": "🍚"},
            {"id": "pasta", "name": "Pasta", "emoji": "🍝"},
            {"id": "bread", "name": "Bread", "emoji": "🍞"},
            {"id": "flour", "name": "Flour", "emoji": "🌾"},
            {"id": "noodles", "name": "Noodles", "emoji": "🍜"},
            {"id": "tortilla", "name": "Tortilla", "emoji": "🫓"},
            {"id": "oats", "name": "Oats", "emoji": "🌾"},
            {"id": "basmati_rice", "name": "Basmati Rice", "emoji": "🍚"},
            {"id": "naan", "name": "Naan", "emoji": "🫓"},
        ]
    },
    "spices": {
        "emoji": "🌶️",
        "items": [
            {"id": "salt", "name": "Salt", "emoji": "🧂"},
            {"id": "pepper", "name": "Black Pepper", "emoji": "🌶️"},
            {"id": "cumin", "name": "Cumin", "emoji": "🫙"},
            {"id": "turmeric", "name": "Turmeric", "emoji": "🟡"},
            {"id": "paprika", "name": "Paprika", "emoji": "🌶️"},
            {"id": "cinnamon", "name": "Cinnamon", "emoji": "🟤"},
            {"id": "chili", "name": "Chili Flakes", "emoji": "🌶️"},
            {"id": "oregano", "name": "Oregano", "emoji": "🌿"},
            {"id": "basil", "name": "Basil", "emoji": "🌿"},
            {"id": "soy_sauce", "name": "Soy Sauce", "emoji": "🫙"},
            {"id": "cilantro", "name": "Cilantro", "emoji": "🌿"},
            {"id": "garam_masala", "name": "Garam Masala", "emoji": "🫙"},
            {"id": "coriander_powder", "name": "Coriander Powder", "emoji": "🫙"},
            {"id": "mustard_seeds", "name": "Mustard Seeds", "emoji": "🫙"},
        ]
    },
    "pantry": {
        "emoji": "🫙",
        "items": [
            {"id": "olive_oil", "name": "Olive Oil", "emoji": "🫒"},
            {"id": "vegetable_oil", "name": "Vegetable Oil", "emoji": "🛢️"},
            {"id": "sugar", "name": "Sugar", "emoji": "🍬"},
            {"id": "honey", "name": "Honey", "emoji": "🍯"},
            {"id": "vinegar", "name": "Vinegar", "emoji": "🫙"},
            {"id": "lemon", "name": "Lemon", "emoji": "🍋"},
            {"id": "coconut_milk", "name": "Coconut Milk", "emoji": "🥥"},
            {"id": "tomato_sauce", "name": "Tomato Sauce", "emoji": "🥫"},
            {"id": "sesame_oil", "name": "Sesame Oil", "emoji": "🫙"},
            {"id": "mayonnaise", "name": "Mayonnaise", "emoji": "🥄"},
            {"id": "ghee", "name": "Ghee", "emoji": "🧈"},
        ]
    }
}

RECIPES = [
    {
        "id": "butter_chicken",
        "title": "Butter Chicken",
        "description": "Creamy, rich, and aromatic Indian curry with tender chicken pieces in a velvety tomato-butter sauce.",
        "image_emoji": "🍛",
        "cuisine": "Indian",
        "difficulty": "Medium",
        "prep_time": 20,
        "cook_time": 35,
        "servings": 4,
        "calories": 490,
        "ingredients": [
            {"name": "chicken", "amount": "500", "unit": "g"},
            {"name": "tomato", "amount": "4", "unit": "pcs"},
            {"name": "butter", "amount": "50", "unit": "g"},
            {"name": "cream", "amount": "100", "unit": "ml"},
            {"name": "onion", "amount": "2", "unit": "pcs"},
            {"name": "garlic", "amount": "4", "unit": "cloves"},
            {"name": "ginger", "amount": "1", "unit": "inch"},
            {"name": "cumin", "amount": "1", "unit": "tsp"},
            {"name": "turmeric", "amount": "0.5", "unit": "tsp"},
            {"name": "chili", "amount": "1", "unit": "tsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Marinate chicken with yogurt, turmeric, chili, and salt for 15 minutes.", "duration": 15, "tip": "The longer you marinate, the more flavorful it gets."},
            {"step": 2, "instruction": "Heat butter in a deep pan. Sauté onions until golden brown.", "duration": 8, "tip": "Low heat helps caramelize the onions evenly."},
            {"step": 3, "instruction": "Add garlic and ginger, cook for 1 minute until fragrant.", "duration": 1, "tip": "Don't burn the garlic — keep stirring."},
            {"step": 4, "instruction": "Add chopped tomatoes and cook until they break down into a sauce.", "duration": 10, "tip": "Cover the pan to speed up the process."},
            {"step": 5, "instruction": "Add cumin and marinated chicken. Cook on medium heat.", "duration": 12, "tip": "Don't overcrowd the pan for better searing."},
            {"step": 6, "instruction": "Pour in cream, stir well, and simmer on low heat for 10 minutes.", "duration": 10, "tip": "Adjust cream for desired richness."},
            {"step": 7, "instruction": "Garnish with fresh cilantro and serve with naan or rice.", "duration": 2, "tip": "A squeeze of lemon elevates the dish."},
        ],
        "tags": ["curry", "creamy", "spicy", "comfort-food"]
    },
    {
        "id": "pasta_aglio_olio",
        "title": "Pasta Aglio e Olio",
        "description": "Classic Italian pasta with garlic, olive oil, and chili flakes — simple yet incredibly flavorful.",
        "image_emoji": "🍝",
        "cuisine": "Italian",
        "difficulty": "Easy",
        "prep_time": 5,
        "cook_time": 15,
        "servings": 2,
        "calories": 380,
        "ingredients": [
            {"name": "pasta", "amount": "200", "unit": "g"},
            {"name": "garlic", "amount": "6", "unit": "cloves"},
            {"name": "olive_oil", "amount": "60", "unit": "ml"},
            {"name": "chili", "amount": "1", "unit": "tsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
            {"name": "pepper", "amount": "0.5", "unit": "tsp"},
            {"name": "basil", "amount": "5", "unit": "leaves"},
        ],
        "steps": [
            {"step": 1, "instruction": "Boil a large pot of salted water and cook pasta until al dente.", "duration": 10, "tip": "Save a cup of pasta water before draining."},
            {"step": 2, "instruction": "Slice garlic thinly. Heat olive oil in a pan on low heat.", "duration": 2, "tip": "Thin slices cook more evenly."},
            {"step": 3, "instruction": "Add garlic to oil and cook slowly until golden (not brown).", "duration": 3, "tip": "Low heat is crucial — burnt garlic tastes bitter."},
            {"step": 4, "instruction": "Add chili flakes and toss in the drained pasta.", "duration": 1, "tip": "Add pasta water a splash at a time for silkiness."},
            {"step": 5, "instruction": "Toss everything together, season with salt and pepper, and garnish with basil.", "duration": 2, "tip": "Fresh parmesan on top takes it to the next level."},
        ],
        "tags": ["quick", "simple", "classic", "vegetarian-optional"]
    },
    {
        "id": "veggie_stir_fry",
        "title": "Asian Veggie Stir Fry",
        "description": "A colorful medley of crisp vegetables tossed in a savory soy-ginger sauce — quick, healthy, and delicious.",
        "image_emoji": "🥘",
        "cuisine": "Asian",
        "difficulty": "Easy",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 3,
        "calories": 220,
        "ingredients": [
            {"name": "bell_pepper", "amount": "2", "unit": "pcs"},
            {"name": "broccoli", "amount": "1", "unit": "cup"},
            {"name": "carrot", "amount": "2", "unit": "pcs"},
            {"name": "mushroom", "amount": "1", "unit": "cup"},
            {"name": "soy_sauce", "amount": "3", "unit": "tbsp"},
            {"name": "garlic", "amount": "3", "unit": "cloves"},
            {"name": "ginger", "amount": "1", "unit": "inch"},
            {"name": "vegetable_oil", "amount": "2", "unit": "tbsp"},
            {"name": "corn", "amount": "0.5", "unit": "cup"},
            {"name": "salt", "amount": "0.5", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Prep all vegetables: slice bell peppers, julienne carrots, chop broccoli.", "duration": 8, "tip": "Cut veggies to similar sizes for even cooking."},
            {"step": 2, "instruction": "Heat oil in a wok on high heat until smoking.", "duration": 1, "tip": "A hot wok is the secret to great stir fry."},
            {"step": 3, "instruction": "Add garlic and ginger, stir for 30 seconds.", "duration": 1, "tip": "Quick stir to prevent burning."},
            {"step": 4, "instruction": "Add carrots and broccoli first (they take longest), cook for 3 minutes.", "duration": 3, "tip": "Keep tossing — don't let anything sit too long."},
            {"step": 5, "instruction": "Add bell peppers, mushrooms, and corn. Stir fry for 3 minutes.", "duration": 3, "tip": "Vegetables should be crisp-tender, not mushy."},
            {"step": 6, "instruction": "Pour soy sauce, toss everything well, and serve hot over rice or noodles.", "duration": 2, "tip": "A dash of sesame oil at the end adds amazing aroma."},
        ],
        "tags": ["healthy", "quick", "vegan", "colorful"]
    },
    {
        "id": "egg_fried_rice",
        "title": "Egg Fried Rice",
        "description": "A quick and satisfying fried rice loaded with scrambled eggs, veggies, and savory soy sauce.",
        "image_emoji": "🍳",
        "cuisine": "Chinese",
        "difficulty": "Easy",
        "prep_time": 5,
        "cook_time": 10,
        "servings": 2,
        "calories": 350,
        "ingredients": [
            {"name": "rice", "amount": "2", "unit": "cups"},
            {"name": "egg", "amount": "3", "unit": "pcs"},
            {"name": "onion", "amount": "1", "unit": "pcs"},
            {"name": "garlic", "amount": "2", "unit": "cloves"},
            {"name": "carrot", "amount": "1", "unit": "pcs"},
            {"name": "peas", "amount": "0.5", "unit": "cup"},
            {"name": "soy_sauce", "amount": "2", "unit": "tbsp"},
            {"name": "vegetable_oil", "amount": "2", "unit": "tbsp"},
            {"name": "salt", "amount": "0.5", "unit": "tsp"},
            {"name": "pepper", "amount": "0.5", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Use day-old cold rice for best results. Break up any clumps.", "duration": 2, "tip": "Freshly cooked rice is too moist and will turn mushy."},
            {"step": 2, "instruction": "Heat oil in a wok. Scramble eggs and set aside.", "duration": 3, "tip": "Cook eggs quickly on high heat for fluffy texture."},
            {"step": 3, "instruction": "Sauté diced onion, garlic, carrots, and peas for 3 minutes.", "duration": 3, "tip": "Dice everything small for even distribution."},
            {"step": 4, "instruction": "Add rice and stir fry on high heat for 3 minutes.", "duration": 3, "tip": "Spread rice in a thin layer and let it get slightly crispy."},
            {"step": 5, "instruction": "Add soy sauce, scrambled eggs, salt, and pepper. Toss well and serve.", "duration": 2, "tip": "Add soy sauce along the edges of the wok for better flavor."},
        ],
        "tags": ["quick", "comfort-food", "easy", "one-pot"]
    },
    {
        "id": "chicken_tacos",
        "title": "Spicy Chicken Tacos",
        "description": "Juicy seasoned chicken wrapped in warm tortillas with fresh toppings and zesty lime.",
        "image_emoji": "🌮",
        "cuisine": "Mexican",
        "difficulty": "Easy",
        "prep_time": 15,
        "cook_time": 12,
        "servings": 4,
        "calories": 420,
        "ingredients": [
            {"name": "chicken", "amount": "400", "unit": "g"},
            {"name": "tortilla", "amount": "8", "unit": "pcs"},
            {"name": "onion", "amount": "1", "unit": "pcs"},
            {"name": "bell_pepper", "amount": "1", "unit": "pcs"},
            {"name": "tomato", "amount": "2", "unit": "pcs"},
            {"name": "lettuce", "amount": "1", "unit": "cup"},
            {"name": "cheese", "amount": "100", "unit": "g"},
            {"name": "lemon", "amount": "1", "unit": "pcs"},
            {"name": "cumin", "amount": "1", "unit": "tsp"},
            {"name": "paprika", "amount": "1", "unit": "tsp"},
            {"name": "chili", "amount": "0.5", "unit": "tsp"},
            {"name": "olive_oil", "amount": "2", "unit": "tbsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Slice chicken into strips. Season with cumin, paprika, chili, and salt.", "duration": 5, "tip": "Let the seasoning sit for 10 minutes for deeper flavor."},
            {"step": 2, "instruction": "Heat olive oil and cook chicken strips until golden and cooked through.", "duration": 8, "tip": "Don't move the chicken too much — let it get a nice sear."},
            {"step": 3, "instruction": "Warm tortillas in a dry pan for 30 seconds each side.", "duration": 3, "tip": "Wrap in a towel to keep them warm and pliable."},
            {"step": 4, "instruction": "Dice tomatoes and onion. Shred lettuce and grate cheese.", "duration": 5, "tip": "A sharp knife makes prep faster and safer."},
            {"step": 5, "instruction": "Assemble tacos: tortilla, chicken, toppings, cheese, and a squeeze of lemon.", "duration": 3, "tip": "Don't overfill — less is more for easier eating."},
        ],
        "tags": ["mexican", "spicy", "fun", "party-food"]
    },
    {
        "id": "mushroom_risotto",
        "title": "Creamy Mushroom Risotto",
        "description": "Luxuriously creamy Italian risotto with earthy mushrooms and parmesan — pure comfort in a bowl.",
        "image_emoji": "🍚",
        "cuisine": "Italian",
        "difficulty": "Medium",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 3,
        "calories": 450,
        "ingredients": [
            {"name": "rice", "amount": "1.5", "unit": "cups"},
            {"name": "mushroom", "amount": "2", "unit": "cups"},
            {"name": "onion", "amount": "1", "unit": "pcs"},
            {"name": "garlic", "amount": "3", "unit": "cloves"},
            {"name": "butter", "amount": "30", "unit": "g"},
            {"name": "cheese", "amount": "50", "unit": "g"},
            {"name": "olive_oil", "amount": "2", "unit": "tbsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
            {"name": "pepper", "amount": "0.5", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Slice mushrooms. Dice onion and mince garlic. Keep 4 cups warm water ready.", "duration": 5, "tip": "Use a mix of mushroom varieties for complex flavor."},
            {"step": 2, "instruction": "Heat olive oil, sauté mushrooms until golden. Set aside.", "duration": 5, "tip": "Don't overcrowd — cook in batches if needed."},
            {"step": 3, "instruction": "In the same pan, melt butter. Cook onion and garlic until soft.", "duration": 4, "tip": "Translucent onions, not browned."},
            {"step": 4, "instruction": "Add rice and stir for 2 minutes until edges turn translucent.", "duration": 2, "tip": "This toasts the rice and creates better texture."},
            {"step": 5, "instruction": "Add warm water one ladle at a time, stirring constantly until absorbed.", "duration": 18, "tip": "Patience is key — this is what makes risotto creamy."},
            {"step": 6, "instruction": "Fold in mushrooms, cheese, salt, and pepper. Serve immediately.", "duration": 2, "tip": "Risotto should flow like lava — add more water if too thick."},
        ],
        "tags": ["comfort-food", "creamy", "vegetarian", "elegant"]
    },
    {
        "id": "paneer_tikka",
        "title": "Paneer Tikka Masala",
        "description": "Grilled paneer cubes in a bold, spiced tomato-cream gravy — a vegetarian showstopper.",
        "image_emoji": "🧀",
        "cuisine": "Indian",
        "difficulty": "Medium",
        "prep_time": 20,
        "cook_time": 25,
        "servings": 4,
        "calories": 410,
        "ingredients": [
            {"name": "paneer", "amount": "300", "unit": "g"},
            {"name": "tomato", "amount": "4", "unit": "pcs"},
            {"name": "onion", "amount": "2", "unit": "pcs"},
            {"name": "yogurt", "amount": "100", "unit": "ml"},
            {"name": "cream", "amount": "50", "unit": "ml"},
            {"name": "garlic", "amount": "4", "unit": "cloves"},
            {"name": "ginger", "amount": "1", "unit": "inch"},
            {"name": "bell_pepper", "amount": "1", "unit": "pcs"},
            {"name": "cumin", "amount": "1", "unit": "tsp"},
            {"name": "turmeric", "amount": "0.5", "unit": "tsp"},
            {"name": "paprika", "amount": "1", "unit": "tsp"},
            {"name": "butter", "amount": "30", "unit": "g"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Cut paneer into cubes. Marinate with yogurt, turmeric, paprika, and salt.", "duration": 15, "tip": "Marinate for at least 30 mins for best results."},
            {"step": 2, "instruction": "Grill or pan-fry paneer cubes and bell pepper until charred edges form.", "duration": 8, "tip": "High heat + minimal oil for the best char."},
            {"step": 3, "instruction": "Blend tomatoes, onion, garlic, and ginger into a smooth paste.", "duration": 3, "tip": "Roasting the tomatoes first adds smokiness."},
            {"step": 4, "instruction": "Heat butter, add cumin, then pour in the tomato paste. Cook for 10 minutes.", "duration": 10, "tip": "Cook until oil separates from the masala."},
            {"step": 5, "instruction": "Add cream, grilled paneer, and simmer for 5 minutes.", "duration": 5, "tip": "Don't boil too long — paneer can become rubbery."},
            {"step": 6, "instruction": "Garnish with cilantro and serve with naan or rice.", "duration": 2, "tip": "A knob of butter on top makes it restaurant-style."},
        ],
        "tags": ["vegetarian", "spicy", "grilled", "rich"]
    },
    {
        "id": "shrimp_scampi",
        "title": "Garlic Butter Shrimp Scampi",
        "description": "Succulent shrimp sautéed in garlic butter with a splash of lemon — elegant yet effortless.",
        "image_emoji": "🦐",
        "cuisine": "Italian",
        "difficulty": "Easy",
        "prep_time": 10,
        "cook_time": 8,
        "servings": 2,
        "calories": 360,
        "ingredients": [
            {"name": "shrimp", "amount": "300", "unit": "g"},
            {"name": "pasta", "amount": "200", "unit": "g"},
            {"name": "garlic", "amount": "5", "unit": "cloves"},
            {"name": "butter", "amount": "40", "unit": "g"},
            {"name": "lemon", "amount": "1", "unit": "pcs"},
            {"name": "chili", "amount": "0.5", "unit": "tsp"},
            {"name": "olive_oil", "amount": "2", "unit": "tbsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
            {"name": "pepper", "amount": "0.5", "unit": "tsp"},
            {"name": "basil", "amount": "5", "unit": "leaves"},
        ],
        "steps": [
            {"step": 1, "instruction": "Cook pasta in salted boiling water. Reserve 1 cup pasta water, then drain.", "duration": 10, "tip": "Slightly undercook pasta — it finishes in the sauce."},
            {"step": 2, "instruction": "Pat shrimp dry. Season with salt, pepper, and chili flakes.", "duration": 2, "tip": "Dry shrimp sear better and don't steam."},
            {"step": 3, "instruction": "Heat olive oil and butter. Cook shrimp 2 minutes per side until pink.", "duration": 4, "tip": "Don't overcook — shrimp goes rubbery quickly."},
            {"step": 4, "instruction": "Add sliced garlic, cook for 1 minute. Squeeze in lemon juice.", "duration": 2, "tip": "The garlic should sizzle gently, not burn."},
            {"step": 5, "instruction": "Toss in pasta with a splash of pasta water. Garnish with basil.", "duration": 2, "tip": "The starchy water helps create a silky sauce."},
        ],
        "tags": ["seafood", "elegant", "quick", "date-night"]
    },
    {
        "id": "chickpea_curry",
        "title": "Spiced Chickpea Curry",
        "description": "Hearty and warming chickpea curry with aromatic spices and coconut milk — vegan comfort food.",
        "image_emoji": "🫘",
        "cuisine": "Indian",
        "difficulty": "Easy",
        "prep_time": 10,
        "cook_time": 25,
        "servings": 4,
        "calories": 310,
        "ingredients": [
            {"name": "chickpeas", "amount": "2", "unit": "cups"},
            {"name": "tomato", "amount": "3", "unit": "pcs"},
            {"name": "onion", "amount": "1", "unit": "pcs"},
            {"name": "garlic", "amount": "3", "unit": "cloves"},
            {"name": "ginger", "amount": "1", "unit": "inch"},
            {"name": "coconut_milk", "amount": "200", "unit": "ml"},
            {"name": "cumin", "amount": "1", "unit": "tsp"},
            {"name": "turmeric", "amount": "0.5", "unit": "tsp"},
            {"name": "chili", "amount": "1", "unit": "tsp"},
            {"name": "spinach", "amount": "2", "unit": "cups"},
            {"name": "vegetable_oil", "amount": "2", "unit": "tbsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Heat oil. Sauté diced onion until golden. Add garlic and ginger.", "duration": 5, "tip": "Medium heat for even caramelization."},
            {"step": 2, "instruction": "Add cumin, turmeric, and chili. Toast spices for 30 seconds.", "duration": 1, "tip": "Toasting blooms the spices and unlocks deeper flavors."},
            {"step": 3, "instruction": "Add chopped tomatoes and cook until they form a thick paste.", "duration": 8, "tip": "Crush the tomatoes with a spoon as they cook."},
            {"step": 4, "instruction": "Add chickpeas and coconut milk. Simmer for 15 minutes.", "duration": 15, "tip": "Mash a few chickpeas for a thicker curry."},
            {"step": 5, "instruction": "Stir in spinach, cook 2 minutes until wilted. Season and serve with rice.", "duration": 2, "tip": "Spinach cooks fast — add it right at the end."},
        ],
        "tags": ["vegan", "healthy", "comfort-food", "one-pot"]
    },
    {
        "id": "french_omelette",
        "title": "Classic French Omelette",
        "description": "Silky, buttery French omelette with melted cheese and fresh herbs — breakfast perfection.",
        "image_emoji": "🥚",
        "cuisine": "French",
        "difficulty": "Easy",
        "prep_time": 5,
        "cook_time": 5,
        "servings": 1,
        "calories": 280,
        "ingredients": [
            {"name": "egg", "amount": "3", "unit": "pcs"},
            {"name": "butter", "amount": "15", "unit": "g"},
            {"name": "cheese", "amount": "30", "unit": "g"},
            {"name": "mushroom", "amount": "0.5", "unit": "cup"},
            {"name": "salt", "amount": "0.25", "unit": "tsp"},
            {"name": "pepper", "amount": "0.25", "unit": "tsp"},
            {"name": "basil", "amount": "3", "unit": "leaves"},
        ],
        "steps": [
            {"step": 1, "instruction": "Crack eggs into a bowl. Season with salt and pepper. Whisk until smooth.", "duration": 1, "tip": "Don't over-whisk — just until yolks and whites are combined."},
            {"step": 2, "instruction": "Sauté sliced mushrooms in a bit of butter until golden. Set aside.", "duration": 3, "tip": "Season mushrooms lightly while cooking."},
            {"step": 3, "instruction": "Melt butter in a non-stick pan on medium-low heat. Pour in eggs.", "duration": 1, "tip": "The butter should foam but not brown."},
            {"step": 4, "instruction": "Gently stir with a spatula, tilting pan to spread uncooked egg.", "duration": 2, "tip": "Keep the heat low — this isn't a scramble."},
            {"step": 5, "instruction": "When just set but still slightly wet on top, add cheese, mushrooms, and basil. Fold and serve.", "duration": 1, "tip": "The residual heat finishes cooking — don't overcook."},
        ],
        "tags": ["breakfast", "quick", "elegant", "vegetarian"]
    },
    {
        "id": "lentil_soup",
        "title": "Hearty Lentil Soup",
        "description": "A nourishing bowl of spiced lentil soup with vegetables — warm, filling, and wholesome.",
        "image_emoji": "🍲",
        "cuisine": "Mediterranean",
        "difficulty": "Easy",
        "prep_time": 10,
        "cook_time": 30,
        "servings": 4,
        "calories": 260,
        "ingredients": [
            {"name": "lentils", "amount": "1.5", "unit": "cups"},
            {"name": "carrot", "amount": "2", "unit": "pcs"},
            {"name": "onion", "amount": "1", "unit": "pcs"},
            {"name": "garlic", "amount": "3", "unit": "cloves"},
            {"name": "tomato", "amount": "2", "unit": "pcs"},
            {"name": "potato", "amount": "1", "unit": "pcs"},
            {"name": "cumin", "amount": "1", "unit": "tsp"},
            {"name": "turmeric", "amount": "0.5", "unit": "tsp"},
            {"name": "lemon", "amount": "1", "unit": "pcs"},
            {"name": "olive_oil", "amount": "2", "unit": "tbsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Rinse lentils thoroughly. Dice all vegetables into small cubes.", "duration": 5, "tip": "Smaller dice = faster cooking and better texture."},
            {"step": 2, "instruction": "Heat olive oil. Sauté onion and garlic until fragrant.", "duration": 3, "tip": "A pinch of cumin in the oil adds extra depth."},
            {"step": 3, "instruction": "Add carrots, potato, tomatoes, and spices. Cook for 3 minutes.", "duration": 3, "tip": "Let the spices coat the vegetables evenly."},
            {"step": 4, "instruction": "Add lentils and 5 cups of water. Bring to boil, then simmer for 25 minutes.", "duration": 25, "tip": "Skim any foam that rises to the top."},
            {"step": 5, "instruction": "Season with salt, squeeze lemon, and serve with bread.", "duration": 2, "tip": "Blend half the soup for a creamy-chunky texture."},
        ],
        "tags": ["vegan", "healthy", "warming", "budget-friendly"]
    },
    {
        "id": "beef_stir_fry",
        "title": "Beef & Broccoli Stir Fry",
        "description": "Tender beef strips with crisp broccoli in a rich, savory sauce — better than takeout.",
        "image_emoji": "🥩",
        "cuisine": "Chinese",
        "difficulty": "Medium",
        "prep_time": 15,
        "cook_time": 12,
        "servings": 3,
        "calories": 440,
        "ingredients": [
            {"name": "beef", "amount": "400", "unit": "g"},
            {"name": "broccoli", "amount": "2", "unit": "cups"},
            {"name": "garlic", "amount": "4", "unit": "cloves"},
            {"name": "ginger", "amount": "1", "unit": "inch"},
            {"name": "soy_sauce", "amount": "3", "unit": "tbsp"},
            {"name": "honey", "amount": "1", "unit": "tbsp"},
            {"name": "vegetable_oil", "amount": "2", "unit": "tbsp"},
            {"name": "corn", "amount": "1", "unit": "tbsp"},
            {"name": "rice", "amount": "2", "unit": "cups"},
            {"name": "salt", "amount": "0.5", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Slice beef thinly against the grain. Marinate with soy sauce and cornstarch.", "duration": 10, "tip": "Freezing beef slightly makes slicing easier."},
            {"step": 2, "instruction": "Blanch broccoli in boiling water for 2 minutes. Drain and set aside.", "duration": 3, "tip": "Ice bath after blanching keeps it bright green."},
            {"step": 3, "instruction": "Heat oil in a wok until smoking. Sear beef in batches for 2 minutes.", "duration": 4, "tip": "High heat + small batches = better sear."},
            {"step": 4, "instruction": "Add garlic and ginger. Stir fry for 30 seconds.", "duration": 1, "tip": "Aromatics go in when the wok is fragrant."},
            {"step": 5, "instruction": "Add broccoli, remaining soy sauce, and honey. Toss well for 2 minutes.", "duration": 2, "tip": "The honey caramelizes and creates a glossy sauce."},
            {"step": 6, "instruction": "Serve hot over steamed rice.", "duration": 2, "tip": "Garnish with sesame seeds and sliced scallions."},
        ],
        "tags": ["protein-rich", "savory", "takeout-style", "meal-prep"]
    },
    {
        "id": "tofu_curry",
        "title": "Coconut Tofu Curry",
        "description": "Crispy tofu cubes swimming in a fragrant coconut curry with vibrant vegetables.",
        "image_emoji": "🍛",
        "cuisine": "Thai",
        "difficulty": "Medium",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 3,
        "calories": 340,
        "ingredients": [
            {"name": "tofu", "amount": "300", "unit": "g"},
            {"name": "coconut_milk", "amount": "200", "unit": "ml"},
            {"name": "bell_pepper", "amount": "1", "unit": "pcs"},
            {"name": "spinach", "amount": "2", "unit": "cups"},
            {"name": "onion", "amount": "1", "unit": "pcs"},
            {"name": "garlic", "amount": "3", "unit": "cloves"},
            {"name": "ginger", "amount": "1", "unit": "inch"},
            {"name": "soy_sauce", "amount": "1", "unit": "tbsp"},
            {"name": "turmeric", "amount": "0.5", "unit": "tsp"},
            {"name": "chili", "amount": "1", "unit": "tsp"},
            {"name": "vegetable_oil", "amount": "3", "unit": "tbsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
            {"name": "rice", "amount": "2", "unit": "cups"},
        ],
        "steps": [
            {"step": 1, "instruction": "Press tofu for 10 minutes, then cut into cubes.", "duration": 12, "tip": "Pressing removes moisture for crispier results."},
            {"step": 2, "instruction": "Pan-fry tofu in oil until golden and crispy on all sides.", "duration": 8, "tip": "Don't flip too often — let each side get properly golden."},
            {"step": 3, "instruction": "Sauté onion, garlic, and ginger until fragrant.", "duration": 3, "tip": "Use the same pan for extra flavor."},
            {"step": 4, "instruction": "Add turmeric, chili, and bell pepper. Cook for 2 minutes.", "duration": 2, "tip": "Let the spices bloom in the oil."},
            {"step": 5, "instruction": "Pour in coconut milk and soy sauce. Simmer for 8 minutes.", "duration": 8, "tip": "Don't boil — gentle simmer keeps the coconut silky."},
            {"step": 6, "instruction": "Add tofu and spinach. Cook 2 minutes. Serve over steamed rice.", "duration": 2, "tip": "Add a squeeze of lime right before serving."},
        ],
        "tags": ["vegan", "creamy", "spicy", "meal-prep"]
    },
    {
        "id": "caprese_salad",
        "title": "Caprese Bruschetta",
        "description": "Fresh tomatoes, creamy cheese, and fragrant basil on crispy toast — Italian simplicity at its finest.",
        "image_emoji": "🍅",
        "cuisine": "Italian",
        "difficulty": "Easy",
        "prep_time": 10,
        "cook_time": 5,
        "servings": 2,
        "calories": 250,
        "ingredients": [
            {"name": "tomato", "amount": "3", "unit": "pcs"},
            {"name": "cheese", "amount": "150", "unit": "g"},
            {"name": "basil", "amount": "10", "unit": "leaves"},
            {"name": "bread", "amount": "4", "unit": "slices"},
            {"name": "olive_oil", "amount": "3", "unit": "tbsp"},
            {"name": "garlic", "amount": "1", "unit": "clove"},
            {"name": "salt", "amount": "0.5", "unit": "tsp"},
            {"name": "pepper", "amount": "0.25", "unit": "tsp"},
            {"name": "vinegar", "amount": "1", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Slice tomatoes and cheese into similar-sized rounds.", "duration": 3, "tip": "Use the ripest tomatoes you can find."},
            {"step": 2, "instruction": "Toast bread slices, rub with a cut garlic clove while warm.", "duration": 3, "tip": "The garlic melts into the warm bread beautifully."},
            {"step": 3, "instruction": "Layer tomato, cheese, and basil on toast.", "duration": 2, "tip": "Alternate colors for a stunning presentation."},
            {"step": 4, "instruction": "Drizzle with olive oil and balsamic vinegar. Season with salt and pepper.", "duration": 1, "tip": "Quality olive oil makes all the difference here."},
        ],
        "tags": ["appetizer", "fresh", "no-cook", "vegetarian"]
    },
    {
        "id": "fish_tacos",
        "title": "Crispy Fish Tacos",
        "description": "Flaky seasoned fish in warm tortillas with crunchy slaw and tangy lime crema.",
        "image_emoji": "🐟",
        "cuisine": "Mexican",
        "difficulty": "Medium",
        "prep_time": 15,
        "cook_time": 10,
        "servings": 4,
        "calories": 380,
        "ingredients": [
            {"name": "fish", "amount": "400", "unit": "g"},
            {"name": "tortilla", "amount": "8", "unit": "pcs"},
            {"name": "cabbage", "amount": "2", "unit": "cups"},
            {"name": "yogurt", "amount": "100", "unit": "ml"},
            {"name": "lemon", "amount": "2", "unit": "pcs"},
            {"name": "flour", "amount": "0.5", "unit": "cup"},
            {"name": "paprika", "amount": "1", "unit": "tsp"},
            {"name": "cumin", "amount": "0.5", "unit": "tsp"},
            {"name": "vegetable_oil", "amount": "3", "unit": "tbsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Cut fish into strips. Mix flour with paprika, cumin, and salt.", "duration": 5, "tip": "Use firm white fish like cod or tilapia."},
            {"step": 2, "instruction": "Coat fish strips in the seasoned flour mixture.", "duration": 3, "tip": "Shake off excess flour for a lighter crust."},
            {"step": 3, "instruction": "Pan-fry fish in hot oil for 3 minutes per side until golden.", "duration": 6, "tip": "Oil should shimmer but not smoke."},
            {"step": 4, "instruction": "Shred cabbage finely. Mix yogurt with lemon juice for crema.", "duration": 4, "tip": "Thin slaw + creamy crema = perfect taco balance."},
            {"step": 5, "instruction": "Warm tortillas, layer fish, slaw, and crema. Squeeze extra lemon.", "duration": 3, "tip": "Char the tortillas slightly for smoky flavor."},
        ],
        "tags": ["seafood", "crispy", "fresh", "taco-tuesday"]
    },
    {
        "id": "sesame_garlic_noodles",
        "title": "Sesame Garlic Noodles",
        "description": "Savory noodles tossed with garlic, soy, sesame oil, and crisp vegetables for a fast weeknight meal.",
        "image_emoji": "🍜",
        "cuisine": "Asian",
        "difficulty": "Easy",
        "prep_time": 10,
        "cook_time": 12,
        "servings": 2,
        "calories": 360,
        "ingredients": [
            {"name": "noodles", "amount": "200", "unit": "g"},
            {"name": "garlic", "amount": "4", "unit": "cloves"},
            {"name": "soy_sauce", "amount": "2", "unit": "tbsp"},
            {"name": "sesame_oil", "amount": "1", "unit": "tbsp"},
            {"name": "carrot", "amount": "1", "unit": "pcs"},
            {"name": "bell_pepper", "amount": "1", "unit": "pcs"},
            {"name": "spring_onion", "amount": "2", "unit": "stalks"},
            {"name": "chili", "amount": "0.5", "unit": "tsp"},
            {"name": "vegetable_oil", "amount": "1", "unit": "tbsp"},
            {"name": "salt", "amount": "0.25", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Cook noodles until just tender, then drain and rinse lightly.", "duration": 6, "tip": "Keep them slightly firm so they do not overcook in the pan."},
            {"step": 2, "instruction": "Whisk soy sauce, sesame oil, chili, and a splash of water into a quick sauce.", "duration": 2, "tip": "A little noodle water helps the sauce cling better."},
            {"step": 3, "instruction": "Heat vegetable oil and saute garlic, carrot, and bell pepper for 3 minutes.", "duration": 3, "tip": "Cut the vegetables thinly so they stay crisp but cook fast."},
            {"step": 4, "instruction": "Add noodles and sauce, then toss until glossy and heated through.", "duration": 2, "tip": "Use tongs to separate the noodles evenly."},
            {"step": 5, "instruction": "Finish with sliced spring onion and serve hot.", "duration": 1, "tip": "Extra sesame oil at the end boosts aroma."},
        ],
        "tags": ["quick", "savory", "weeknight", "vegetarian"]
    },
    {
        "id": "paneer_tikka_skillet",
        "title": "Paneer Tikka Skillet",
        "description": "Golden paneer cooked with yogurt spices, peppers, and onions for an easy stovetop tikka-style dinner.",
        "image_emoji": "🧀",
        "cuisine": "Indian",
        "difficulty": "Medium",
        "prep_time": 15,
        "cook_time": 15,
        "servings": 3,
        "calories": 410,
        "ingredients": [
            {"name": "paneer", "amount": "300", "unit": "g"},
            {"name": "yogurt", "amount": "100", "unit": "ml"},
            {"name": "bell_pepper", "amount": "1", "unit": "pcs"},
            {"name": "onion", "amount": "1", "unit": "pcs"},
            {"name": "garlic", "amount": "3", "unit": "cloves"},
            {"name": "ginger", "amount": "1", "unit": "inch"},
            {"name": "cumin", "amount": "1", "unit": "tsp"},
            {"name": "paprika", "amount": "1", "unit": "tsp"},
            {"name": "turmeric", "amount": "0.5", "unit": "tsp"},
            {"name": "lemon", "amount": "1", "unit": "pcs"},
            {"name": "olive_oil", "amount": "2", "unit": "tbsp"},
            {"name": "salt", "amount": "0.75", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Cube the paneer and mix it with yogurt, garlic, ginger, cumin, paprika, turmeric, and salt.", "duration": 8, "tip": "A short marinade still adds plenty of flavor."},
            {"step": 2, "instruction": "Slice onion and bell pepper into thick strips.", "duration": 3, "tip": "Larger pieces stay juicy and char nicely."},
            {"step": 3, "instruction": "Heat olive oil in a skillet and sear paneer until golden on two sides.", "duration": 5, "tip": "Do not overcrowd the pan or the paneer will steam."},
            {"step": 4, "instruction": "Add onion and bell pepper, then cook until lightly charred and tender.", "duration": 5, "tip": "A little color gives the dish its tikka-style flavor."},
            {"step": 5, "instruction": "Finish with a squeeze of lemon and serve with rice or flatbread.", "duration": 1, "tip": "Fresh cilantro on top is a great finishing touch."},
        ],
        "tags": ["spiced", "vegetarian", "skillet", "protein-rich"]
    },
    {
        "id": "black_bean_quesadilla",
        "title": "Black Bean Quesadilla",
        "description": "Crispy tortillas stuffed with black beans, cheese, and vegetables for a fast, satisfying meal.",
        "image_emoji": "🫓",
        "cuisine": "Mexican",
        "difficulty": "Easy",
        "prep_time": 10,
        "cook_time": 10,
        "servings": 2,
        "calories": 390,
        "ingredients": [
            {"name": "black_beans", "amount": "1", "unit": "cup"},
            {"name": "tortilla", "amount": "4", "unit": "pcs"},
            {"name": "cheese", "amount": "120", "unit": "g"},
            {"name": "tomato", "amount": "1", "unit": "pcs"},
            {"name": "onion", "amount": "0.5", "unit": "pcs"},
            {"name": "bell_pepper", "amount": "0.5", "unit": "pcs"},
            {"name": "cumin", "amount": "0.5", "unit": "tsp"},
            {"name": "paprika", "amount": "0.5", "unit": "tsp"},
            {"name": "olive_oil", "amount": "1", "unit": "tbsp"},
            {"name": "salt", "amount": "0.5", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Mash the black beans lightly and mix with cumin, paprika, and salt.", "duration": 3, "tip": "Leave some whole beans for a better texture."},
            {"step": 2, "instruction": "Dice tomato, onion, and bell pepper into small pieces.", "duration": 3, "tip": "Smaller pieces help the quesadilla stay closed."},
            {"step": 3, "instruction": "Lay filling and cheese over half of each tortilla, then fold closed.", "duration": 2, "tip": "Do not overfill or the cheese will spill out."},
            {"step": 4, "instruction": "Cook in a lightly oiled skillet until both sides are crisp and the cheese melts.", "duration": 4, "tip": "Press gently with a spatula for even browning."},
            {"step": 5, "instruction": "Slice and serve warm.", "duration": 1, "tip": "Serve with yogurt or salsa for extra freshness."},
        ],
        "tags": ["quick", "vegetarian", "crispy", "budget-friendly"]
    },
    {
        "id": "avocado_chickpea_wrap",
        "title": "Avocado Chickpea Wrap",
        "description": "Creamy avocado and chickpeas wrapped with crunchy vegetables and a bright yogurt dressing.",
        "image_emoji": "🌯",
        "cuisine": "Fusion",
        "difficulty": "Easy",
        "prep_time": 12,
        "cook_time": 0,
        "servings": 2,
        "calories": 320,
        "ingredients": [
            {"name": "avocado", "amount": "1", "unit": "pcs"},
            {"name": "chickpeas", "amount": "1", "unit": "cup"},
            {"name": "tortilla", "amount": "2", "unit": "pcs"},
            {"name": "cucumber", "amount": "1", "unit": "pcs"},
            {"name": "tomato", "amount": "1", "unit": "pcs"},
            {"name": "lettuce", "amount": "1", "unit": "cup"},
            {"name": "yogurt", "amount": "3", "unit": "tbsp"},
            {"name": "lemon", "amount": "1", "unit": "pcs"},
            {"name": "cilantro", "amount": "2", "unit": "tbsp"},
            {"name": "salt", "amount": "0.5", "unit": "tsp"},
            {"name": "pepper", "amount": "0.25", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Mash avocado with lemon juice, salt, and pepper until creamy.", "duration": 3, "tip": "Leave it slightly chunky for better texture."},
            {"step": 2, "instruction": "Fold chickpeas and chopped cilantro into the avocado mixture.", "duration": 2, "tip": "Mash a few chickpeas to help the filling hold together."},
            {"step": 3, "instruction": "Slice cucumber and tomato, then rinse and dry the lettuce.", "duration": 3, "tip": "Dry lettuce keeps the wraps from getting soggy."},
            {"step": 4, "instruction": "Spread yogurt over tortillas, then add lettuce, vegetables, and the avocado chickpea filling.", "duration": 3, "tip": "Warm the tortillas briefly if you want softer wraps."},
            {"step": 5, "instruction": "Roll tightly, slice in half, and serve.", "duration": 1, "tip": "Wrap in parchment if you are packing them to go."},
        ],
        "tags": ["no-cook", "fresh", "vegetarian", "lunch"]
    },
    {
        "id": "aloo_gobi",
        "title": "Aloo Gobi",
        "description": "A classic Indian dry sabzi with potatoes, cauliflower, and warming spices.",
        "image_emoji": "🥔",
        "cuisine": "Indian",
        "difficulty": "Easy",
        "prep_time": 15,
        "cook_time": 25,
        "servings": 4,
        "calories": 240,
        "ingredients": [
            {"name": "potato", "amount": "2", "unit": "pcs"},
            {"name": "cauliflower", "amount": "1", "unit": "medium"},
            {"name": "onion", "amount": "1", "unit": "pcs"},
            {"name": "tomato", "amount": "2", "unit": "pcs"},
            {"name": "ginger", "amount": "1", "unit": "inch"},
            {"name": "garlic", "amount": "3", "unit": "cloves"},
            {"name": "turmeric", "amount": "0.5", "unit": "tsp"},
            {"name": "cumin", "amount": "1", "unit": "tsp"},
            {"name": "coriander_powder", "amount": "1", "unit": "tsp"},
            {"name": "garam_masala", "amount": "0.5", "unit": "tsp"},
            {"name": "vegetable_oil", "amount": "2", "unit": "tbsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Cut potatoes and cauliflower into medium florets and cubes.", "duration": 5, "tip": "Keep the pieces similar in size so they cook evenly."},
            {"step": 2, "instruction": "Heat oil and saute cumin, onion, ginger, and garlic until fragrant.", "duration": 5, "tip": "Do not brown the garlic too much."},
            {"step": 3, "instruction": "Add tomato, turmeric, coriander powder, and salt. Cook into a masala base.", "duration": 6, "tip": "Cook until the oil begins to separate slightly."},
            {"step": 4, "instruction": "Add potato and cauliflower, toss well, cover, and cook until tender.", "duration": 10, "tip": "Sprinkle a little water if the masala starts sticking."},
            {"step": 5, "instruction": "Finish with garam masala and serve hot with roti or rice.", "duration": 2, "tip": "Do not overcook if you want the cauliflower to keep some bite."},
        ],
        "tags": ["indian", "home-style", "vegetarian", "dry-curry"]
    },
    {
        "id": "chana_masala",
        "title": "Chana Masala",
        "description": "A hearty North Indian chickpea curry simmered in a spicy onion-tomato gravy.",
        "image_emoji": "🍛",
        "cuisine": "Indian",
        "difficulty": "Medium",
        "prep_time": 15,
        "cook_time": 30,
        "servings": 4,
        "calories": 310,
        "ingredients": [
            {"name": "chickpeas", "amount": "2", "unit": "cups"},
            {"name": "onion", "amount": "2", "unit": "pcs"},
            {"name": "tomato", "amount": "3", "unit": "pcs"},
            {"name": "garlic", "amount": "4", "unit": "cloves"},
            {"name": "ginger", "amount": "1", "unit": "inch"},
            {"name": "green_chili", "amount": "1", "unit": "pcs"},
            {"name": "cumin", "amount": "1", "unit": "tsp"},
            {"name": "turmeric", "amount": "0.5", "unit": "tsp"},
            {"name": "coriander_powder", "amount": "1.5", "unit": "tsp"},
            {"name": "garam_masala", "amount": "0.75", "unit": "tsp"},
            {"name": "cilantro", "amount": "2", "unit": "tbsp"},
            {"name": "vegetable_oil", "amount": "2", "unit": "tbsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Blend or finely chop onion, tomato, ginger, garlic, and green chili.", "duration": 8, "tip": "A smoother masala gives restaurant-style texture."},
            {"step": 2, "instruction": "Heat oil, add cumin, then cook the onion-tomato mixture until thickened.", "duration": 10, "tip": "Be patient here because this builds most of the flavor."},
            {"step": 3, "instruction": "Stir in turmeric, coriander powder, garam masala, and salt.", "duration": 2, "tip": "Add a splash of water if the spices start catching."},
            {"step": 4, "instruction": "Add chickpeas and simmer with a little water until the gravy coats them well.", "duration": 8, "tip": "Mash a spoonful of chickpeas to naturally thicken the curry."},
            {"step": 5, "instruction": "Finish with cilantro and serve with naan or rice.", "duration": 2, "tip": "A squeeze of lemon just before serving brightens the dish."},
        ],
        "tags": ["indian", "protein-rich", "vegan", "curry"]
    },
    {
        "id": "jeera_rice",
        "title": "Jeera Rice",
        "description": "Fragrant basmati rice tempered with cumin and ghee, perfect alongside curries and dals.",
        "image_emoji": "🍚",
        "cuisine": "Indian",
        "difficulty": "Easy",
        "prep_time": 5,
        "cook_time": 20,
        "servings": 4,
        "calories": 210,
        "ingredients": [
            {"name": "basmati_rice", "amount": "1.5", "unit": "cups"},
            {"name": "cumin", "amount": "2", "unit": "tsp"},
            {"name": "ghee", "amount": "1", "unit": "tbsp"},
            {"name": "salt", "amount": "0.75", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Wash basmati rice until the water runs mostly clear, then soak briefly.", "duration": 5, "tip": "Soaking helps the grains cook long and separate."},
            {"step": 2, "instruction": "Heat ghee and let the cumin sizzle until aromatic.", "duration": 2, "tip": "Do not let the cumin burn or it will taste bitter."},
            {"step": 3, "instruction": "Add drained rice and stir gently to coat in the ghee.", "duration": 2, "tip": "This adds extra fragrance to the finished rice."},
            {"step": 4, "instruction": "Add water and salt, cover, and cook until the rice is tender.", "duration": 10, "tip": "Keep the heat low once it comes to a simmer."},
            {"step": 5, "instruction": "Rest for 5 minutes, fluff gently, and serve.", "duration": 1, "tip": "A short rest keeps the grains from breaking."},
        ],
        "tags": ["indian", "side-dish", "rice", "fragrant"]
    },
    {
        "id": "palak_paneer",
        "title": "Palak Paneer",
        "description": "Soft paneer cubes in a creamy spinach gravy flavored with garlic, cumin, and garam masala.",
        "image_emoji": "🥬",
        "cuisine": "Indian",
        "difficulty": "Medium",
        "prep_time": 15,
        "cook_time": 20,
        "servings": 4,
        "calories": 330,
        "ingredients": [
            {"name": "paneer", "amount": "250", "unit": "g"},
            {"name": "spinach", "amount": "4", "unit": "cups"},
            {"name": "onion", "amount": "1", "unit": "pcs"},
            {"name": "tomato", "amount": "1", "unit": "pcs"},
            {"name": "garlic", "amount": "4", "unit": "cloves"},
            {"name": "ginger", "amount": "1", "unit": "inch"},
            {"name": "green_chili", "amount": "1", "unit": "pcs"},
            {"name": "cumin", "amount": "1", "unit": "tsp"},
            {"name": "garam_masala", "amount": "0.5", "unit": "tsp"},
            {"name": "cream", "amount": "2", "unit": "tbsp"},
            {"name": "ghee", "amount": "1", "unit": "tbsp"},
            {"name": "salt", "amount": "1", "unit": "tsp"},
        ],
        "steps": [
            {"step": 1, "instruction": "Blanch spinach briefly, cool it, and blend into a smooth puree.", "duration": 5, "tip": "Do not overcook the spinach or the color will dull."},
            {"step": 2, "instruction": "Heat ghee and saute cumin, onion, garlic, ginger, and green chili.", "duration": 5, "tip": "Cook until the onion softens and turns lightly golden."},
            {"step": 3, "instruction": "Add tomato and cook into the masala base.", "duration": 4, "tip": "The masala should lose its raw smell before moving on."},
            {"step": 4, "instruction": "Stir in spinach puree, garam masala, cream, and salt, then simmer gently.", "duration": 4, "tip": "Keep the heat low to preserve the bright green color."},
            {"step": 5, "instruction": "Add paneer cubes, cook for 2 minutes, and serve with naan or jeera rice.", "duration": 2, "tip": "Do not simmer paneer too long or it can turn chewy."},
        ],
        "tags": ["indian", "vegetarian", "creamy", "restaurant-style"]
    },
]


def get_all_ingredients():
    """Return all ingredients as a flat list with category info."""
    result = []
    for cat_id, cat_data in INGREDIENT_CATEGORIES.items():
        for item in cat_data["items"]:
            result.append({
                **item,
                "category": cat_id,
                "category_emoji": cat_data["emoji"]
            })
    return result


def get_ingredient_names():
    """Return a set of all ingredient IDs for quick lookup."""
    names = set()
    for cat_data in INGREDIENT_CATEGORIES.values():
        for item in cat_data["items"]:
            names.add(item["id"])
    return names
